import { name, version } from '../package.json'
import { config } from './config'
import { toPyImport } from './utils'
import * as eta from 'eta'

const template = `
__doc__ = '''
This file is generated by the \`${name} (${version})\`,
Please do not modify directly.

repository: https://github.com/mao-shonen/prisma-client-py-tortoise-orm
'''

import typing
from enum import Enum
from tortoise import fields
from tortoise.models import Model
<% it.extendImports.forEach(len => { %>
<%= len %>
<% }) %>

`.trimStart()

export const renderTemplate = async (): Promise<string> => {
  const extendImports = []

  if (config.sourceClassFile) {
    extendImports.push(toPyImport(config.sourceClassFile) + ' as base')
  }

  const formatData = {
    extendImports,
  }

  return (await eta.render(template, formatData)) as string
}
