import { name, version } from '../package.json'

export const template = `
__doc__ = '''
This file is generated by the \`${name} (${version})\`,
Please do not modify directly.

repository: https://github.com/mao-shonen/prisma-client-py-tortoise-orm
'''

import typing
from enum import Enum
from tortoise import fields
from tortoise.models import Model

`.trimStart()
